import { SectionShell } from './SectionShell'
import { MethodologyWalkthrough } from '@/components/methodology/MethodologyWalkthrough'
import { TopRankedCallout } from './TopRankedCallout'
import { Pullquote } from './Pullquote'
import { GlossaryTerm } from '@/components/ui/GlossaryTerm'

export function MethodologyMadeVisible() {
  return (
    <SectionShell id="methodology" eyebrow="The methodology, made visible">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
        <h2 className="
            col-span-1 lg:col-span-12
            font-serif font-light text-ivory leading-[1.05]
            text-4xl sm:text-5xl lg:text-6xl
            max-w-[22ch]
          ">
          How a framework finds the sites that earn the next dollar.
        </h2>

        <div className="
            col-span-1 lg:col-span-8 lg:col-start-3
            mt-2
            font-sans text-body text-ivory-dim font-light leading-[1.65]
          ">
          <p>
            Over twenty-six weeks, Natrx and Billion Oyster Project built the
            methodology together. More than thirty datasets were evaluated.
            Four collaborative workshops were held with BOP&apos;s science
            team. Two custom data products were generated by{' '}
            <GlossaryTerm termId="natrx-assess">
              <em className="font-serif italic text-white">Natrx Assess</em>
            </GlossaryTerm>
            .
          </p>
          <p className="mt-6">
            The framework asks two questions in order. First, where can
            oysters thrive? Three water-quality variables, scored across all
            78 candidates. Second, what do the surrounding conditions add or
            subtract? Wave energy, shoreline change, permitting context,
            mission fit. The framework mixes both dimensions, calibrated to
            each location. It&apos;s a way of asking where the natural world
            and the built one strengthen each other, in one specific place.
            The walkthrough below moves through the analysis in the order it
            was built: biology first, then the external factors.
          </p>
        </div>
      </div>

      {/* Pullquote between intro and walkthrough */}
      <div className="mt-16 lg:mt-20">
        <Pullquote
          attribution="Mike McCann"
          role="Director of Science and Research, Billion Oyster Project"
        >
          What we have now is a ranking and a confidence layer attached to
          every site. That&apos;s where the science comes in. We&apos;re
          never certain. But knowing where we&apos;re confident and where
          we&apos;re not is exactly what we want when we&apos;re making
          these decisions.
        </Pullquote>
      </div>

      {/* Map 2 + spectra panel — the six-step guided sequence */}
      <div className="mt-16 lg:mt-20">
        <MethodologyWalkthrough />
      </div>

      {/* Top-ranked sites callouts — three editorial cards nested inside the section */}
      <div className="mt-20 lg:mt-28">
        <div className="font-mono text-eyebrow uppercase tracking-[0.22em] text-ivory-faint mb-6">
          What the ranking surfaces
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 lg:gap-8">
          <TopRankedCallout
            name="Arthur Kill"
            meta="Rank 1 · Score 0.87 · Staten Island, Upper Harbor"
            siteIds={['27']}
            body={
              <>
                The strongest site in the pipeline sits on the industrial west
                shore of Staten Island, a stretch of harbor that spent the
                twentieth century synonymous with degradation. The water there
                now shows the strongest combination of salinity, chlorophyll-a,
                and dissolved oxygen for oyster restoration anywhere across the
                78 candidates.
              </>
            }
          />
          <TopRankedCallout
            name="Living Breakwaters cluster"
            meta="Ranks 2–7 · Scores 0.79 to 0.74 · Raritan Bay"
            siteIds={['36', '37', '38', '40', '41', '42']}
            body={
              <>
                Six locations within the Living Breakwaters system, the
                SCAPE-designed resilience installation off Tottenville, share
                the second through seventh positions in the ranking. The
                waters around Living Breakwaters are among the strongest
                candidates in the harbor for further reef restoration.
              </>
            }
          />
          <TopRankedCallout
            name="Wolfe's Pond"
            meta="Rank 8 · Score 0.65 · Raritan Bay"
            siteIds={['30']}
            body={
              <>
                Wolfe&apos;s Pond Park is publicly accessible Staten Island
                parkland. The site scores strongly on every water quality
                variable and presents manageable conditions across wave
                exposure and shoreline change.
              </>
            }
          />
        </div>
      </div>
    </SectionShell>
  )
}
